/**
 * Copyright (C) 2008 Germano Fronza
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * To contact the author:
 *  - germano.inf@gmail.com
 */
package br.furb.inf.tcc.server;

import java.io.Serializable;

import br.furb.inf.tcc.tankcoders.game.PlayerTank;
import br.furb.inf.tcc.tankcoders.game.PlayerType;

/**
 * Player online.
 * @author Germano Fronza
 */
public class OnlinePlayer implements Serializable {

	private static final long serialVersionUID = 1L;

	/**
	 * Same id generated by JGN.
	 */
	private short playerId;
	
	/**
	 * Name of the player (not tank name)
	 */
	private String playerName;
	
	/**
	 * Type of the player.
	 */
	private PlayerType playerType;
	
	/**
	 * Ip Address of the player.
	 */
	private String ipAddress;
	
	/**
	 * Names of all tanks of this player.
	 */
	private PlayerTank[] tanks;
	
	/**
	 * User is ready to play.
	 */
	private boolean readyToPlay;
	
	/**
	 * Player is playing.
	 */
	private boolean playing;
	
	public short getPlayerId() {
		return playerId;
	}

	public void setPlayerId(short playerId) {
		this.playerId = playerId;
	}

	public String getPlayerName() {
		return playerName;
	}

	public void setPlayerName(String playerName) {
		this.playerName = playerName;
	}

	public boolean isReadyToPlay() {
		return readyToPlay;
	}

	public void setReadyToPlay(boolean readyToPlay) {
		this.readyToPlay = readyToPlay;
	}

	public String getIpAddress() {
		return ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	public PlayerTank[] getTanks() {
		return tanks;
	}

	public PlayerTank getTankByName(String tankName) {
		for (PlayerTank pTank : tanks) {
			if (pTank.getTankName().equals(tankName)) {
				return pTank;
			}
		}
		
		return null;
	}
	
	public void setTanks(PlayerTank[] tanks) {
		this.tanks = tanks;
	}

	public PlayerType getPlayerType() {
		return playerType;
	}

	public void setPlayerType(PlayerType playerType) {
		this.playerType = playerType;
	}
	
	public String toString() {
		return "Player id: " + playerId + ", Name: " + playerName + ", Qty. tanks: " + tanks.length;
	}

	public boolean isPlaying() {
		return playing;
	}

	public void setPlaying(boolean playing) {
		this.playing = playing;
	}
}
